### ISSUE TITLE
Send fake http response

### ISSUE THREAD

**Issue by delikelli** [PcapDotNet/Pcap.Net#100]
I have captured network traffic based on filtered host name such as www.google.com. I wanna then change / attack to http response of my request. For example,when I entered google, browser will return fake response with html I prepared. While i am trying to send some http response layer, wireshark say to me spurious. Can I do it with pcap?

**Comment by bricknerb** [comment]
Please use https://groups.google.com/forum/#!forum/pcapdotnet.
