### ISSUE TITLE
PcapDotNet on virtual machine

### ISSUE THREAD

**Issue by microkost** [PcapDotNet/Pcap.Net#101]
Hello everyone!

I can't run my projects using PcapDotNet on any **virtual PC** including newest and also older OS (Win 7, Win 10, Win 2016). 

I am getting error of **System.TypeInitializationException cannot load assembly or one of its dependencies PcapDotNet.Core.dll**. Same build is working on physical computer. WinPcap is of course installed. It doesn't matter if it's virtualized on VmWare or Hyper-V or hosted in Azure.

I tried to check dependency problem, tool [Dependencies](https://github.com/lucasg/Dependencies) found missing msvcr100.dll and msvcp100.dll, but adding them to run folder didn't change program behaviour. It is failing when runned from compiled file as same as from locally builded.

Did was anyone facing same issue or even found a solution?

**Comment by bricknerb** [comment]
Please use [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
See the [FAQ](https://github.com/PcapDotNet/Pcap.Net/wiki/FAQ) for an answer for your question.
