### ISSUE TITLE
Sealed classes is pain to extend

### ISSUE THREAD

**Issue by solaristhesun** [PcapDotNet/Pcap.Net#104]
How am I supposed to extend your classes if you make them all sealed?

I would like to parse a proprietary protocol based on ethernet. Deriving from EthernetDatagram does not work because EthernetDatagram is sealed. Deriving from EthernetBaseDiagram does not work because constructor is internal.

What approach do you recommend? What is the point in making these class sealed? What harm is done if someone derives from your classes?

**Comment by solaristhesun** [comment]
I tried to derive from DataSegment, but doesn't work either because I cannot really access the buffer. I can call ReadMacAddress but not ReadUShort for example. Lot of useful functions are internal.

**Comment by bricknerb** [comment]
Use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.

Only Pcap.Net's API is public.
You're welcome to fork and make changes.
You're also welcome to contribute changes, including making things more public.
Changes would be accepted if they make sense with the general ideas behind Pcap.Net.
