### ISSUE TITLE
Does it support EtherCAT frame filter?

### ISSUE THREAD

**Issue by hyzhappy** [PcapDotNet/Pcap.Net#105]
I want to capture EtherCAT frame. But the filter syntax seems to not recognize the EtherCAT. The code below did not work.

```C#
var pc = dev.Open(65536, PacketDeviceOpenAttributes.Promiscuous, 1000);
var filter = pc.CreateFilter("ether proto ecat");
pc.SetFilter(filter);
```
But the EthernetType enumeration has EtherCatProtocol. How can I capture EtherCAT frame

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
