### ISSUE TITLE
Incorrect device description compared to dumpcap -D, tshark -D output

### ISSUE THREAD

**Issue by draeder** [PcapDotNet/Pcap.Net#106]
Dumpcap/Tshark output appears like this:

```
C:\Program Files\Wireshark>tshark -D
1. \Device\NPF_{5D8D8B7E-D095-4A98-A0ED-D6D9BA4527DB} (Ethernet)
2. \Device\NPF_{3817F026-A68E-4FE1-B3DE-BFC18D26981E} (vEthernet (Internet))
3. \Device\NPF_{61442FCB-D358-4699-B83B-66AB777233DE} (Bluetooth Network Connection)
```

Using the example provided here, https://github.com/PcapDotNet/Pcap.Net/wiki/Pcap.Net-Tutorial-Obtaining-the-device-list, the description does not match dumpcap or tshark output.

`Console.WriteLine(" (" + device.Description + ")");` appears like this:

```
1. rpcap://\Device\NPF_{5D8D8B7E-D095-4A98-A0ED-D6D9BA4527DB} (Network adapter 'Intel(R) 82579V Gigabit Network Connection' on local host)
2. rpcap://\Device\NPF_{3817F026-A68E-4FE1-B3DE-BFC18D26981E} (Network adapter 'Microsoft Corporation' on local host)
3. rpcap://\Device\NPF_{61442FCB-D358-4699-B83B-66AB777233DE} (Network adapter 'Microsoft' on local host)
```

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.

I'm not sure why do you expect the `Description` to be equivalent to what tshark -D prints.
It's quite possible that tshark uses different properties beyond the device description to describe the device.
You can use `Attributes` and `Addresses` to get more information.
Also, you can use `LivePacketDeviceExtensions.GetNetworkInterface` to get even more information.
