### ISSUE TITLE
NullReferenceException when trying to access UDP ports?

### ISSUE THREAD

**Issue by ketchums** [PcapDotNet/Pcap.Net#108]
Running this sample code in my packet handler.

```
IpV4Datagram ip = packet.Ethernet.IpV4;
UdpDatagram udp = ip.Udp;
Console.WriteLine(udp.SourcePort);
```

Throws a NullReferenceException when trying to access the var udp

> System.NullReferenceException: Object reference not set to an instance of an object

Is there a trigger / reason why this would be null? Or is this unexpected (a bug)? It throws this exception on all packets being captured, so I don't think its an issue with a certain packet.

**Comment by ketchums** [comment]
The full exception text.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Coyote.Core.Network.NetworkHandler.OnPacket(Packet packet) in C:\Users\admin\Desktop\Coyote\Coyote.Core\Network\NetworkHandler.cs:line 90
>    at PcapDotNet.Core.PacketCommunicator.PacketHandler.Handle(Byte* user, pcap_pkthdr* packetHeader, Byte* packetData) in c:\github\pcap.net\pcapdotnet\src\pcapdotnet.core\packetcommunicator.cpp:line 343
>    at pcap_loop(pcap* , Int32 , IntPtr , Byte* )
>    at PcapDotNet.Core.PacketCommunicator.ReceivePackets(Int32 count, HandlePacket callback) in c:\github\pcap.net\pcapdotnet\src\pcapdotnet.core\packetcommunicator.cpp:line 181
>    at Coyote.Core.Network.NetworkHandler.FetchPackets() in C:\Users\admin\Desktop\Coyote\Coyote.Core\Network\NetworkHandler.cs:line 79
>    at Coyote.Core.Commands.Networking.SniffPacketsCommand.Process(String[] arguments, ICoreContext coreContext) in C:\Users\admin\Desktop\Coyote\Coyote.Core\Commands\Networking\SniffPacketsCommand.cs:line 48
>    at Coyote.Core.Commands.ConsoleCommandProvider.Process(String content, ICoreContext coreContext) in C:\Users\admin\Desktop\Coyote\Coyote.Core\Commands\ConsoleCommandProvider.cs:line 49

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
