### ISSUE TITLE
When Sending TCP Packets using PCAP.NET the TCP Options are not visible on Wireshark? My goal is actually to maniupulate the Selective Acknowledgement option... but I can't even see the options to begin with.

### ISSUE THREAD

**Issue by kcd2412** [PcapDotNet/Pcap.Net#110]
// TCP Layer
                TcpLayer tcpLayer = new TcpLayer
                {
                    SourcePort = _sourcePort,
                    DestinationPort = _destinationPort,
                    SequenceNumber = _seqNumber,
                    ControlBits = TcpControlBits.Synchronize,
                    Window = _windowSize,
                };

                communicator.SendPacket(PacketBuilder.Build(DateTime.Now, ethernetLayer, ipV4Layer, tcpLayer));
                _expectedAckNumber = _seqNumber + 1;

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
