### ISSUE TITLE
How to stop send packet? (Trasmit())

### ISSUE THREAD

**Issue by semenov-ch** [PcapDotNet/Pcap.Net#111]
I use the `trasmit()` method to send packets and I want to be able to cancel sending. How can I do it?

```
using (outputCommunicator = outputDevice.Open(100, PacketDeviceOpenAttributes.Promiscuous, 1000))
{
     outputCommunicator.Transmit(sendBuffer, true);
}
```

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
