### ISSUE TITLE
pcap.h not found compile time on PcapDotNet.Core module

### ISSUE THREAD

**Issue by ugrozkr** [PcapDotNet/Pcap.Net#113]
I downloaded project and open from VS 2017 when i clicked to build solution i got failed bacause PcapDotNet.Core main module can not found pcap.h reference in project. How can i find this library ?

**Comment by ugrozkr** [comment]
can you help us @shargon  @bricknerb @FlorianHockmann

**Comment by bricknerb** [comment]
Please use the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) to ask questions.
