### ISSUE TITLE
Support for Linux SLL datalink

### ISSUE THREAD

**Issue by bricknerb** [PcapDotNet/Pcap.Net#40]
<b>brianestey17[CodePlex]</b> <br />I have captured a pcap file using Tao tPacketCapture on Android (http://www.taosoftware.co.jp/en/android/packetcapture/). The problem is that the pcap file I captured has
 a datalink of quotLINUX_SLL (Linux cooked)quot and this throws an exception 'packet.IsValid' threw an exception of type 'System.NotSupportedException'base {System.SystemException} = {quotPcapDataLink 113 - LINUX_SLL (Linux cooked) is unsupportedquot}I've
 attached the pcap file in question.

**Comment by bricknerb** [comment]
<b>Brickner[CodePlex]</b> <br />Just committed changeset 71055, which adds support for Linux SLL datalink.
This would be supported in the next version of Pcap.Net or in any version you download the source for and build yourself starting from changeset 71055.

**Comment by hanvyj** [comment]
Is there a way to actually parse it, or does it just not reject the packets?

**Comment by bricknerb** [comment]
I suggest asking in [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) and provide an sample of packet you want to parse and what exactly doesn't work for you.
