### ISSUE TITLE
Create ability to block packets from being passed on to windows driver

### ISSUE THREAD

**Issue by bricknerb** [PcapDotNet/Pcap.Net#41]
<b>menkaur[CodePlex]</b> <br />I'm trying to use Pcap.Net to bypass winsockets altogether and to send packets directly. I must do this, because RAW sockets are supported only on the server class windows operating systems. I want to do this, because Pcap.Net is much better suited for
 low level network interactions than raw sockets (better structure, ability to access Ethernet layer ect).

My problem is that, as it is, the packets that are received are passed on to windows driver, which creates bad interactions.

Consider flowing: I'm trying to open a tcp connection to the host. I send the SYN package and it sends me back SYN-ACK package. Before I can confirm the connection for open, Windows driver, which processes the SYN-ACK package sends RST package to close the
 connection. At present, there's nothing I can do about this issue.

**Comment by bricknerb** [comment]
<b>Brickner[CodePlex]</b> <br />You should use a system / drivers / devices that aren't interfering with the packets you don't want them to interfere.
Pcap.Net is a WinPcap wrapper and WinPcap doesn't block packets.
I'll close this issue, since it's out of the scope of Pcap.Net and isn't planned to be supported in a future version, unless you want to change the feature request.

**Comment by TheCodingCaesar** [comment]
I also had the same issue, I fixed this by using windivert library. I captured all RST packets using windivert before it reaches windows TCP stack. There is a c# wrapper is also available for windivert named Divert.Net
