### ISSUE TITLE
When a IpV4 packet is fragmented, sometimes it returns a zero length IpV4Datagram.

### ISSUE THREAD

**Issue by bricknerb** [PcapDotNet/Pcap.Net#44]
<b>sumtec[CodePlex]</b> <br />According to https://en.wikipedia.org/wiki/IPv4, when a ipv4 packet is fragmented, the total length should be the length of the current segment. However, in the real world, I found that the
 total length could be zero when there are payload and the ip4v packet is marked quotMore Fragmentationsquot. In this case, the code now will return no data inside ipv4 packet, i.e. no TCP packet, which is not correct.

**Comment by bricknerb** [comment]
<b>sumtec[CodePlex]</b> <br />Yes, I will try to capture one, maybe next week.

**Comment by bricknerb** [comment]
<b>Brickner[CodePlex]</b> <br />Can you give me a .pcap file example for the case you suggest?

**Comment by poinda** [comment]
Hi @bricknerb 
I've just encountered this same issue and can provide a pcap file for debug purposes. Pcap.net reports an invalid packet yet examining the packet in wireshark shows it reconstructing correctly. 
In trying to diagnose the issue I came across http://rtoodtoo.net/generic_segmentation_offload_and_wireshark/ and in turn, 
 https://en.wikipedia.org/wiki/Large_segment_offload.
I will email a pcap file to pcapdotnet@gmail.com which you can hopefully use to assist in identifying and debugging the issue.
Grateful if you could get a fix in :)
Thanks very much for your work!
Cheers.

**Comment by bricknerb** [comment]
Thanks for the example.
Wireshark indeed reports:
"
Total Length: 1629 bytes (reported as 0, presumed to be because of "TCP segmentation offload" (TSO))
"

**Comment by bricknerb** [comment]
I've committed 69c3a1fafb6dd0b644de4a9544ba581543f6a571 that should fix this.
