### ISSUE TITLE
ICMP Support

### ISSUE THREAD

**Issue by bricknerb** [PcapDotNet/Pcap.Net#6]
<b>Brickner[CodePlex]</b> <br />Add support for ICMP datagrams (over IPv4).
Should looks like this:
Packet packet;
packet.Ethernet.IpV4.Icmp...

**Comment by muphblu** [comment]
Hi. What's about ICMPv6? I can't find it, is it implemented?

**Comment by bricknerb** [comment]
Try packet.Ethernet.IpV6.Icmp
