### ISSUE TITLE
Broken Download

### ISSUE THREAD

**Issue by hennyC** [PcapDotNet/Pcap.Net#61]
I clicked the "download zip" option and cannot find a single dll file in there?
What files do I reference in my project and where do I get them?

Thank you

**Comment by bricknerb** [comment]
Hi hennyC,

For questions on Pcap.Net, please see the [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet).

"Download ZIP" button is a GitHub feature for downloading the latest code.
To download a release version, see the [releases tab.](https://github.com/PcapDotNet/Pcap.Net/releases).

Boaz.
