### ISSUE TITLE
Pcap.Net.x86 is compiled as a x86?

### ISSUE THREAD

**Issue by dcparga** [PcapDotNet/Pcap.Net#63]
Hi,

I need to install a utility that uses Pcap.Net, and I installed the x86 version, as it should go to a 32bit machine. The problem is that running the program gives me that error:

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'PcapDotNet.Core, Version=1.0.3.20978, Culture=neutral, PublicKeyToken=4b6f3e583145a652' or one of its dependencies. An attempt was made to load a program with an incorrect format.

So, that makes me think that the package 1.0.3 x86 is actually compiled as a 64 bit dll.

Best Regards,

Dani

**Comment by bricknerb** [comment]
More likely it means that you are missing one of the dependencies.
Please make sure you've followed the full instructions in [Using Pcap.Net in your programs page](https://github.com/PcapDotNet/Pcap.Net/wiki/Using-Pcap.Net-in-your-programs)
If this still doesn't work, please give more details by opening a discussion in [Pcap,Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet)
The issues here are for known bugs or feature requests.
