### ISSUE TITLE
find a bug, 0 byte of PCap file will be unable to release the reference of it.

### ISSUE THREAD

**Issue by luoshangyu** [PcapDotNet/Pcap.Net#64]
Hi author,

Repro:
1. read a pcap file
2. the pcap file size is 0.
3. read it.
4. then delete the current file

Result:
the file size is 0 byte.
then throws exception that I'm unable to delete the file.
exception is: due to the file is used by the current process, I'm unable to delete.

Exception:
Failed opening file E:\Git\ Balabala_iPhone_4.3.2. Error: truncated dump file; tried to read 24 file header bytes, only got 0.

My current workaround:
try to see if the file size is less or equal than zero, if yes, delete it instead of read it by using pcap.net lib API.

Best Regards,
Lucas Luo

**Comment by bricknerb** [comment]
I couldn't reproduce this.
I've tried the following code:
```
const string Filename = @"C:\SomeEmptyFile.pcap";
OfflinePacketDevice device = new OfflinePacketDevice(Filename);
using (PacketCommunicator communicator = device.Open())
{
}
```

Pcap.Net does throw an exception, because it is indeed an invalid pcap file.
After the program ends, I can delete the file.

What is the bug?

**Comment by luoshangyu** [comment]
does your pcap file contains zero bytes? I'm really unable to delete the file because the file is being used by the current process. below is how i open the file. but when quit using, the file is not released by pcap, from the behavior that I saw.

                    using (PacketCommunicator communicator =
                    selectedDevice.Open(65535, PacketDeviceOpenAttributes.Promiscuous, 1000))
                {
                    try
                    {
                        communicator.ReceivePackets(0, DispatcherHandler);
                    }
                    catch (InvalidOperationException invalidOptEx)
                    {
                        Console.WriteLine("balabala");
                    }
                }

**Comment by bricknerb** [comment]
When opening an empty file I get this exception (as expected):

A first chance exception of type 'System.InvalidOperationException' occurred in PcapDotNet.Core.dll

Additional information: Failed opening file D:\Users\Boaz\Downloads\empty.pcap. Error: truncated dump file; tried to read 24 file header bytes, only got 0.
