### ISSUE TITLE
how to receive packets simultaneously and pass them to thread individually

### ISSUE THREAD

**Issue by dovson** [PcapDotNet/Pcap.Net#67]
How can i receive packets using pcap.net simultaneously and pass them to different thread. Or how to use threads to handle each packet received
i have a code below but its not working though
public sub 1()
Using filter As BerkeleyPacketFilter = communicator.CreateFilter("ether dst " + Privateinterfacemacaddress + " and not dst host 192.168.1.110")
communicator.SetFilter(filter)
End Using
PacketReceivingThread = New Thread(New ThreadStart(Sub() communicator.ReceivePackets(0, AddressOf PacketReceiver) End Sub))
PacketReceivingThread.IsBackground = True
PacketReceivingThread.Start()
End Sub

Private Sub PacketReceiver(ByVal receivedpacket As Packet)
msgbox("packet received")
' process packet
End Sub

it should keep on producing messagebox on the screen but its only producing one at a time which means it will proccess one packet after the other.How can i make it proccess the packet as it it received.i want it to receive each packet and pass each packet to its own thread so that the thread proccess.I am trying to achieve exactly like the asynchronous sockets

**Comment by bricknerb** [comment]
Question on how to use Pcap.Net should be in https://groups.google.com/forum/#!forum/pcapdotnet.
Though I'm not sure this question is about Pcap.Net. It might just about how to use Threads in .NET.
