### ISSUE TITLE
Best way to determine type of received packet

### ISSUE THREAD

**Issue by vanikcz** [PcapDotNet/Pcap.Net#70]
Dear PCAP.NET team,
can you help me with a best way to determine a packet type? For example, if I have capture filter like that (tcp port 80) or (udp port 53).
How can I safely determine a type of packet? Sorry for maybe dumb question, but Im unable to find the answer in other ways...

Best regards
Jan

**Comment by bricknerb** [comment]
Hi Jan,

Please use the [Pcap.Net Q&A group](https://groups.google.com/forum/#!forum/pcapdotnet).

Boaz.
