### ISSUE TITLE
Problem with first tutorial

### ISSUE THREAD

**Issue by beppe9000** [PcapDotNet/Pcap.Net#71]
I ported the first tutorial to Vb.Net but I get an exception. Looks like a dependency error.
I got Pcap.Net from  Nuget (the Pcap.Net.x64 package) Can somebody help me fix this?

> System.BadImageFormatException has not been handled
>   FileName=PcapDotNet.Core, Version=1.0.3.21026, Culture=neutral, PublicKeyToken=4b6f3e583145a652
>   FusionLog==== Pre-bind state information ===
> LOG: DisplayName = PcapDotNet.Core, Version=1.0.3.21026, Culture=neutral, PublicKeyToken=4b6f3e583145a652
>  (Fully-specified)
> LOG: Appbase = file:///C:/Users/b9k/Documents/Visual Studio 2015/Projects/pMon/pMon/bin/Debug/
> LOG: Initial PrivatePath = NULL
> Calling assembly : pMon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
> =<x>=<x>=
> LOG: This bind starts in default load context.
> LOG: Using application configuration file: C:\Users\b9k\Documents\Visual Studio 2015\Projects\pMon\pMon\bin\Debug\pMon.vshost.exe.config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Post-policy reference: PcapDotNet.Core, Version=1.0.3.21026, Culture=neutral, PublicKeyToken=4b6f3e583145a652
> LOG: Attempting download of new URL file:///C:/Users/b9k/Documents/Visual Studio 2015/Projects/pMon/pMon/bin/Debug/PcapDotNet.Core.DLL.
> ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.
> 
>   HResult=-2147024885
>   Message=Could not load file or assembly 'PcapDotNet.Core, Version=1.0.3.21026, Culture=neutral, PublicKeyToken=4b6f3e583145a652' or one of its dependencies. Tried loading an incorrect format.
>   Source=pMon
>   StackTrace:
>        at pMon.modPcap.ListDevices()
>        at pMon.Form1.startup() in C:\Users\b9k\Documents\Visual Studio 2015\Projects\pMon\pMon\Form1.vb:line 9
>        at pMon.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\b9k\Documents\Visual Studio 2015\Projects\pMon\pMon\Form1.vb:line 3
>        at System.EventHandler.Invoke(Object sender, EventArgs e)
>        at System.Windows.Forms.Form.OnLoad(EventArgs e)
>        at System.Windows.Forms.Form.OnCreateControl()
>        at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>        at System.Windows.Forms.Control.CreateControl()
>        at System.Windows.Forms.Control.WmShowWindow(Message& m)
>        at System.Windows.Forms.Control.WndProc(Message& m)
>        at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>        at System.Windows.Forms.Form.WmShowWindow(Message& m)
>        at System.Windows.Forms.Form.WndProc(Message& m)
>        at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>        at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>        at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*There are some localized messages that i translated at my best...*

WinPcap is installed, but i didn't choose to enable drivers at boot time. Do I have to enable them manually or the library does?

This is the ported code:

```
Sub ListDevices()
        ' Retrieve the device list from the local machine
        Dim allDevices As IList(Of LivePacketDevice) = LivePacketDevice.AllLocalMachine
        If allDevices.Count = 0 Then
            Console.WriteLine("No interfaces found! Make sure WinPcap is installed.")
            Return
        End If
        ' Print the list
        Dim i As Integer = 0
        While i <> allDevices.Count
            Dim device As LivePacketDevice = allDevices(i)
            Console.Write((i + 1) + ". " + device.Name)
            If device.Description IsNot Nothing Then
                Console.WriteLine(" (" + device.Description + ")")
            Else
                Console.WriteLine(" (No description available)")
            End If
            i += 1
        End While
    End Sub
```

**Comment by bricknerb** [comment]
Please see question 6 in the [FAQ](https://github.com/PcapDotNet/Pcap.Net/wiki/FAQ).

If you still have an issue, use the [Pcap.Net Q&A group](https://groups.google.com/forum/#!forum/pcapdotnet).

**Comment by beppe9000** [comment]
So that Nuget package is not official?

**Comment by HalfDeadPie** [comment]
Hello, I would like to ask you how did you solve this problem. thank you.

**Comment by bricknerb** [comment]
If you still have an issue, use the [Pcap.Net Q&A group](https://groups.google.com/forum/#!forum/pcapdotnet).

**Comment by AndriyBogdan** [comment]
I solved this problem. You need to install WinPcap - https://www.winpcap.org/install/default.htm. And after that you can use PcapDotNet library futures. This is .NET wrapper for WinPcap and it can not work without WinPcap.

**Comment by gdhdgwrefgr** [comment]
For anyone else having this error, I just typed `sc start npf` in command prompt as an administrator. Fixed the issue.
