### ISSUE TITLE
How to modify a packet to send it to proxy?

### ISSUE THREAD

**Issue by nammmmm** [PcapDotNet/Pcap.Net#77]
Hello,
I would like to know what changes i have to make to a packet that is gonna be sent through direct connection, to make it go through a proxy instead?
Is Pcap.Net able to do this?

example:
a packet is gonna be sent to google, (direct connection)
Pcap.Net intercept it,
Tamper it,
and send the modified packet (so it goes through proxy then google)

**Comment by bricknerb** [comment]
Please use [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) for questions.
