### ISSUE TITLE
IPv4 header is parsed incorrectly

### ISSUE THREAD

**Issue by DarkDaskin** [PcapDotNet/Pcap.Net#78]
Try to read a packet from the attached PCAP file. The IPv4 header of the packet will contain garbage values, and the payload will be misaligned. Using live capture leads to the same result. Both x86 and x64 NuGet packages contain this bug.

WireShark installed on the same machine has no problems parsing my packets.

[udp.zip](https://github.com/PcapDotNet/Pcap.Net/files/430866/udp.zip)

**Comment by bricknerb** [comment]
I'm reading this packet using packet.Ethernet.IpV4 and it seems to contain non garbage values.
If you still encounter issues, please open a discussion in [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet) with more details on how you try to read this file (code).

**Comment by DarkDaskin** [comment]
OK, now I see where I was wrong. I was using `packet.IpV4` instead.
