### ISSUE TITLE
IPv4 in not decoded correctly inside GRE

### ISSUE THREAD

**Issue by paulbir** [PcapDotNet/Pcap.Net#81]
I have a packet with these layers:
Ethernet > IPv4 >GRE (PPP) > IPv4 > UDP
And inside GRE IPv4 layer is decoded wrong.
I've attached wireshark pcapng with this packet and raw byte data.

Thanks.
[packet.zip](https://github.com/PcapDotNet/Pcap.Net/files/529967/packet.zip)

**Comment by bricknerb** [comment]
Please ask questions in [Pcap.Net Q&A group](https://groups.google.com/forum/#!forum/pcapdotnet).

Also provide the code you're using to decode, what is your expected result and what is the actual result.
