### ISSUE TITLE
packet.IpV4.Source and packet.IpV4.CurrentDestination is error

### ISSUE THREAD

**Issue by dreamincode2015** [PcapDotNet/Pcap.Net#87]
packet.IpV4.Source and packet.IpV4.CurrentDestination is error，You should take the IP packet, but take it from the data frame,
this my screen print  www.lantunnel.com/imgs/errorip.png  (copy this url ,Paste to browser)
 
private static void PacketHandler(Packet packet)
        {
            Console.WriteLine(string.Format("Source IP:{0},DestinationIP:{1}   size{2} ", packet.IpV4.Source, packet.IpV4.CurrentDestination, packet.Length ));
            Console.WriteLine("\r\n--------10 hexadecimal------");
            foreach (var b in packet.Buffer)
                Console.Write(Convert.ToString(b, 10) + ",");
            Console.WriteLine("\r\n--------16 hexadecimal------");
            foreach (var b in packet.Buffer)
                Console.Write(Convert.ToString(b, 16) + ",");           
            Console.WriteLine(packet.Timestamp.ToString("yyyy-MM-dd hh:mm:ss.fff") + " length:" + packet.Length);
            Console.WriteLine("");
        }

**Comment by bricknerb** [comment]
Please provide a .pcap file so it can be debugged.

**Comment by dreamincode2015** [comment]
I have found the reason

Cannot access packet.IpV4.Source

This access is correct packet.Ethernet.IpV4
