### ISSUE TITLE
Suggest add capability of change packet content to Packet Class

### ISSUE THREAD

**Issue by Tom-Lu** [PcapDotNet/Pcap.Net#92]
Firstly, I'm aware of WinPcap only able to perform packet capture not injection. But in some case we do need change packet content, like the project I'm current working on. I implemented kind of bridge application to redirect packets from Tap Adapter to Physical Ethernet Adapter, and I need change packet content like IP Address, add/remove Vlan layer. It's not easy to do so with current design. This just my suggestion.

**Comment by bricknerb** [comment]
You can create packets using `Layer`s extracted from existing `Packet`'s `Datagram`s.
You can change the layers properties and create a new Packet from them.
WinPcap does allow injecting packets and Pcap.Net provides that functionality.
I'm not aware that anything you suggest is particularly hard to do with current design.

See:
* https://github.com/PcapDotNet/Pcap.Net/wiki/Pcap.Net-Tutorial-Sending-Packets
* https://groups.google.com/forum/#!searchin/pcapdotnet/change$20packet%7Csort:relevance/pcapdotnet/3TDjxFVs7qY/l0HbLZGhCgAJ

**Comment by Tom-Lu** [comment]
What I mean about packet injection is change packet content before it reach TCP stack or application layer.
Yes, we could create new Packet from existing one, but that's not the most efficient way.
