### ISSUE TITLE
DNS Sniffing

### ISSUE THREAD

**Issue by WildyDodo** [PcapDotNet/Pcap.Net#95]
Hello,
I'm writing a child-safe tool in c#. I'm using PcapDotNet to intercept requests. Before i was intercepting only HTTP frames, but now I'm trying to intercept DNS queries, parse them to a blacklist and spoof the response with "127.0.0.1" to block the website. Only one problem: i have the DnsDatagram from the packet but I dont understand how could I have the domain queried from the computer. I hope you can help me. (Sorry for my bad english, I'm italian ahah)

**Comment by bricknerb** [comment]
`dnsDatagram.Queries` should give you the list of queries (which should have a single item).
Please post questions on Pcap.Net in [Pcap.Net Q&A Group](https://groups.google.com/forum/#!forum/pcapdotnet).
