### ISSUE TITLE
Duplicate frames in Wireshark

### ISSUE THREAD

**Issue by TheCodingCaesar** [PcapDotNet/Pcap.Net#98]
Hi Guys,

I have created a whole TCP/IP stack using Pcapdotnet and c#. 
But in some PCs wire-shark shows a duplicate frames for all the packets send with the Pcapdotnet. Please see the [Screenshot](https://lh3.googleusercontent.com/-cZqMP3WTP_I/WnrmR9iJumI/AAAAAAAACv8/WDWlADRxnGAqJNwWp5uIP4sMnLFHFCy0wCLcBGAs/s1600/2017-12-21.png)

Here Frame no.s 303, 306 and 308 are sent using pcapdotnet and 304,307 and 309 are the respective duplicates.
These duplicate frames are not reaching the destination or on the network. 
This issues are only observed in some Windows PCs.

Only using communicator.send() once for sending a packet.
See the attached log. 169.254.242.137 is using Pcapdotnet stack
[Issue.zip](https://github.com/PcapDotNet/Pcap.Net/files/1702998/Issue.zip)

Is anyone can help me on this?

**Comment by bricknerb** [comment]
It's unclear this is an issue with Pcap.Net.
Without a way to reproduce this, there's no clear AI for this issue.
I'm closing this and the discussion on this can be continued in https://groups.google.com/forum/#!topic/pcapdotnet/P9JMZr0J-Ko.

**Comment by egz01** [comment]
@TheCodingCaesar I assume you're the original poster of this question:
https://stackoverflow.com/questions/48663902/duplicate-frames-in-wireshark-pcapdotnet/57192292#57192292

If you're curious, I think I found an answer.
