### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by delikelli** [PcapDotNet/Pcap.Net#99]
Hi,  I got the nuget packages of pcapdotnet. While I am trying to get devices list as a first operation, an error occurs such as "an unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll Additional information: Could not load file or assembly 'PcapDotNet.Core, Version=1.0.4.25149, Culture=neutral, PublicKeyToken=06a20bc2fabb1931' or one of its dependencies. An attempt was made to load a program with an incorrect format."
I have installed winpcap driver and tested it with wireshark. I have windows 10 and visual studio 2015 with .net framework 4.7.1 and also installed some c++ redistributable packages but there is still same problem...

**Comment by bricknerb** [comment]
See question 6 in the FAQ.
https://github.com/PcapDotNet/Pcap.Net/wiki/FAQ
